In [1]:
import numpy as np 

from matplotlib import pyplt as plt

ImportError: cannot import name 'pyplt' from 'matplotlib' (c:\python\lib\site-packages\matplotlib\__init__.py)

In [16]:
# operaters types
#1 arthimatic operators "+,-,/,*"
#2 relation operators "<,>,==,>=,<=,!="
#3 logical operatos "&,|"
...............................
#1 arthimatic operators


In [9]:
#1 arthimatic operators "+,-,/,*"
a = 3
b = 4
a + b
a/b
a!=b

True

In [5]:
#2 relation operators "<,>,==,>=,<="
a>b
a<b

True

In [12]:
#3 logical operatos "&,|"
c= True
d = False
c&d
d|c

True

In [23]:
my_str = " Hello Word! "
my_str.lower()
my_str.upper()
my_str.count("l")


2

In [24]:
len(my_str)

11

In [26]:
my_str.replace('H','J')

'Jello Word!'

In [27]:
my_str.find("Word")

6

In [28]:
my_str

'Hello Word!'

In [30]:
my_str.split(" ")

['Hello', 'Word!']

In [37]:
tup1 = (1,True,3.14,'a')
tup1

(1, True, 3.14, 'a')

In [45]:
tup1[0:2]

(1, True)

In [51]:
tup2 = (1,2,3)
tup3 = (4,4,6)


In [55]:
tup2[0] + tup3[1]

5

In [65]:
a= tup3*3 + tup2
a

(4, 4, 6, 4, 4, 6, 4, 4, 6, 1, 2, 3)

In [62]:
min(a)

1

In [63]:
max(a)

6

In [66]:
l1 = [1,'asad','3.4',4]
type(l1)

list

In [67]:
l1[2]

'3.4'

In [71]:
l1[0]=2
l1

[2, 'asad', '3.4']

In [70]:
l1

[2, 'asad', '3.4']

In [72]:
l1.append(1)
l1

[2, 'asad', '3.4', 1]

In [74]:
l1.pop(2)
l1

[2, 'asad']

In [75]:
l = ['apple','orange','banana','cheery']
l

['apple', 'orange', 'banana', 'cheery']

In [77]:
l.insert(3,"mango")
l

['apple', 'orange', 'banana', 'mango', 'cheery']

In [80]:
l.sort()
l

['apple', 'banana', 'cheery', 'mango', 'orange']

In [81]:
dic = {"name": 'Asad',"age":34}
dic

{'name': 'Asad', 'age': 34}

In [334]:
dic.keys()

dict_keys(['age', 'name', 'address', 'height', 'roll_no'])

In [335]:
dic.values()

dict_values([35, 'asad', '58 gosha', 34, 'R-1212'])

In [336]:
dic["age"] = 70
dic

{'age': 70,
 'name': 'asad',
 'address': '58 gosha',
 'height': 34,
 'roll_no': 'R-1212'}

In [87]:
dic.pop("name")
dic

{'age': 35}

In [92]:
dic2 = {"name":'asad','address':'58 gosha'}
dic.update(dic2)
dic

{'age': 35, 'name': 'asad', 'address': '58 gosha'}

In [104]:
dic['height'] = 34
dic

{'age': 35,
 'name': 'asad',
 'address': '58 gosha',
 1: 'height',
 0: 'height',
 'namw': 'height',
 'height': 34}

In [111]:
dic.pop('namw')
dic

{'age': 35, 'name': 'asad', 'address': '58 gosha', 'height': 34}

In [112]:
dic

{'age': 35, 'name': 'asad', 'address': '58 gosha', 'height': 34}

In [114]:
dic['roll_no']= 'R-1212'
dic

{'age': 35,
 'name': 'asad',
 'address': '58 gosha',
 'height': 34,
 'roll_no': 'R-1212'}

In [119]:
dic.keys()
dic

{'age': 35,
 'name': 'asad',
 'address': '58 gosha',
 'height': 34,
 'roll_no': 'R-1212'}

In [122]:
s1 = {1,3.14,'spara',3.14}
s1.update(['hello', 66767,5j])
s1

{1, 3.14, 5j, 66767, 'hello', 'spara'}

In [123]:
s1.add('False')
s1

{1, 3.14, 5j, 66767, 'False', 'hello', 'spara'}

In [124]:
s1.remove('spara')
s1

{1, 3.14, 5j, 66767, 'False', 'hello'}

In [129]:
s2 = {1,3,5}
s3 = {5,7,5}
s2.union(s3)


{1, 3, 5, 7}

In [132]:
# if Statemets Loop

if(5>5):
    print('True')
else:
    print('False')

False


In [148]:
if (5>6) | (5>5):
    print('True')    
elif (6>5) &(6<4):
    print('True')   
else:
    print('Flase')
    

Flase


In [150]:
d1 = ('z','s','d')

In [152]:
if 'a' in d1:
    print('True')
else:
    print('False')

False


In [153]:
d = {"name":['ali','asad','hina'],
    "age":[32,23,45],
    "height":[12,43,66]}
d

{'name': ['ali', 'asad', 'hina'], 'age': [32, 23, 45], 'height': [12, 43, 66]}

In [157]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [155]:
import pandas as pd
pd.DataFram(d)

AttributeError: module 'pandas' has no attribute 'DataFram'

In [158]:
#Class
class Phone():
    def make_call(self):
        print('I am making a call')
    def play_game(self):
        print('play game')
p1 = Phone()
p1.make_call()
p1.play_game()

I am making a call
play game


In [159]:
class Phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print('I am making a call')
    def play_game(self):
        print('play game')
 

In [160]:
p2 = Phone()

In [162]:
p2.set_color('red')
p2.set_cost(46666)

In [165]:
p2.show_color()


'red'

In [166]:
p2.show_cost()

46666

In [187]:
class Employee:
    def __init__(self,name,age,salary): #constructor
        self.name = name;
        self.age = age;
        self.salary =salary;
    def Employee_details(self): #normal method
        print("Name of employee is "+self.name)
        print("Age of employee"+ self.age)
        print("Salary of employee"+ self.salary)

In [195]:
e1 = Employee('Arslan',' 34',' 30000') #object
e1.Employee_details()

Name of employee is Arslan
Age of employee 34
Salary of employee 30000


In [198]:
class Company(Employee):
    def user_details(self):
        print(self.name +' is Employee of this Company')
        print(self.age +' Age')
e2 = Company("Arslan",'24','30000')
e2.user_details()

Arslan is Employee of this Company
24 is Age


In [217]:
class Vehical:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    def show_vehical_details(self):
        print('Meleage of Vehical is ',self.mileage)
        print('Cost of Vehical is ',self.cost)
        print('I am car')

In [218]:
V1 = Vehical('300','500')

In [219]:
V1.show_vehical_details()

Meleage of Vehical is  300
Cost of Vehical is  500
I am car


In [223]:
class Car(Vehical):
    def show_car_details(self):
        print('I am Vehical')

In [224]:
c1 = Car(300,500)
c1.show_car_details()

I am Vehical


In [225]:
c1.show_vehical_details()

Meleage of Vehical is  300
Cost of Vehical is  500
I am car


In [254]:
class vehical:
    def __init__(self,mil,cost):
        self.mileage = mil
        self.cost = cost
    def show_vehical_details(self):
        print('Meleage  ',self.mil)
        print('Cost of  ',self.cost)
        print(' car')

In [255]:
v1 = vehical(300,500)

In [257]:
C1 = Car(600,10000,8,999)

In [291]:
# Multiple inheritance 2 Parent in 1 Child
class Parent1:
    def assign_string_one(self,str1):
        self.str1 = str1
    def show_string_one(self):
        return self.str1

In [284]:
class Parent2:
    def assign_string_two(self,str2):
        self.str2 = str2
    def show_string_two(self):
        return self.str2

In [285]:
class Child(Parent1,Parent2):
    def assign_string_three(self,str3):
        self.str3 = str3
    def show_string_three(self):
        return self.str3

In [286]:
my_child = Child()

In [287]:
my_child.assign_string_one("I am string of parent 1")

In [288]:
my_child.assign_string_two("I am string of parent 2")

In [289]:
my_child.assign_string_three("I am string of parent 3")

In [290]:
my_child.show_string_one()

'I am string of parent 1'

In [281]:
my_child.show_string_two()

'I am string of parent 2'

In [282]:
my_child.show_string_three()

'I am string of parent 3'

In [ ]:
#Multiple Inhiretence

In [292]:
class Parent:
    def get_name(self,name):
        self.name = name
    def show_name(self):
        return self.name


In [294]:
class Child(Parent):
    def get_age(self,age):
        self.age = age
    def show_age(self):
        return self.age

In [295]:
class Grand_Child(Child):
    def get_gender(self,gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [297]:
gc = Grand_Child() 

In [300]:
gc.get_name('Arslan')
gc.get_age(34)
gc.get_gender('Male')

In [302]:
gc.show_name()


'Arslan'

In [303]:
gc.show_age()


34

In [304]:
gc.show_gender()

'Male'

In [305]:
import numpy as np

In [306]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [307]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [310]:
a.shape

(2, 4)

In [312]:
l1 = [3.45,5,6]

In [313]:
n1 = np.array(l1)

In [321]:
type(n1)

numpy.ndarray

In [323]:
n3 = np.zeros((10,10))

In [339]:
import pandas as pd

In [341]:
n2 = pd.DataFrame(n3)

In [344]:
n2.columns = list("ABCDEFGHIJ")

In [345]:
n2

A    B    C    D    E    F    G    H    I    J
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [346]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [350]:
np4 = np.full((3,3),10)

In [348]:
np4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [351]:
np5 = np.arange(10,20) #print 10-19
np5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [353]:
np6 = np.arange(5,51,5) #gape 5
np6

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [360]:
np1 = np.random.randint(5,51,5) #olny 5 number

In [361]:
np1

array([26, 34, 30, 48, 43])

In [365]:

np4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [366]:
np4.shape

(3, 3)

In [370]:
np4.shape = (9,1)

In [371]:
np4

array([[10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10],
       [10]])

In [372]:
n1 = np.array([1,2,3])

In [373]:
n2 = np.array([2,3,4])

In [377]:
np.vstack((n2,n1))

array([[2, 3, 4],
       [1, 2, 3]])

In [379]:
np.hstack((n2,n1))

array([2, 3, 4, 1, 2, 3])

In [381]:
np.column_stack((n1,n2))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [382]:
np.intersect1d(n1,n2) #duplicate value

array([2, 3])

In [385]:
np.setdiff1d(n2,n1)

array([4])

In [386]:
np.setdiff1d(n1,n2)

array([1])

In [392]:
n1 = [10,20]
n2 = [30,40]

In [393]:
np.sum([n1,n2])

100

In [396]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [401]:
np3=np.array([10,40,30])
np.mean(np3)

26.666666666666668

In [402]:
np.median(np3)

30.0

In [414]:
p1 = pd.Series([1,2,3,4])

In [415]:
p1

0    1
1    2
2    3
3    4
dtype: int64

In [430]:
a = 2.4

In [436]:
str(a)


'2.4'

In [435]:
type(a)

float

In [467]:
p2 = pd.Series({'a':20,'b':30,'c':50})

In [468]:
p3 = pd.Series({'d':10,'e':60,'f':70})

In [469]:
p2+p3

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
dtype: float64

In [470]:
s1 = pd.Series([1,2,3])
s2 = pd.Series([4,5,7])
s1+s2

0     5
1     7
2    10
dtype: int64

In [484]:
x= pd.DataFrame({"name":['Ali','Asad','hassam'],"age":[23,45,33]})
x

name  age
0     Ali   23
1    Asad   45
2  hassam   33

In [483]:
x.to_csv("dic.csv",index = False)

In [491]:
y = x.loc[:2,('name')]
y

0       Ali
1      Asad
2    hassam
Name: name, dtype: object

In [493]:
df = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [494]:
df

0         1         2         3         4
0    0.326001  0.932996  0.417699  0.913155  0.103338
1    0.739126  0.146782  0.933030  0.910299  0.089911
2    0.837405  0.329110  0.433011  0.296106  0.473252
3    0.036361  0.784073  0.256466  0.654225  0.445484
4    0.045914  0.537175  0.494367  0.963783  0.887703
..        ...       ...       ...       ...       ...
329  0.780272  0.234274  0.057274  0.364951  0.087924
330  0.916470  0.978719  0.614011  0.585698  0.855150
331  0.723955  0.915197  0.202361  0.771998  0.810760
332  0.029631  0.450812  0.085161  0.254788  0.785794
333  0.747321  0.558879  0.072716  0.511503  0.366573

[334 rows x 5 columns]

In [498]:
df.drop(2,axis =1)

0         1         3         4
0    0.326001  0.932996  0.913155  0.103338
1    0.739126  0.146782  0.910299  0.089911
2    0.837405  0.329110  0.296106  0.473252
3    0.036361  0.784073  0.654225  0.445484
4    0.045914  0.537175  0.963783  0.887703
..        ...       ...       ...       ...
329  0.780272  0.234274  0.364951  0.087924
330  0.916470  0.978719  0.585698  0.855150
331  0.723955  0.915197  0.771998  0.810760
332  0.029631  0.450812  0.254788  0.785794
333  0.747321  0.558879  0.511503  0.366573

[334 rows x 4 columns]

In [501]:
df.loc[0][1] = 67
df

0          1         2         3         4
0    0.326001  67.000000  0.417699  0.913155  0.103338
1    0.739126   0.146782  0.933030  0.910299  0.089911
2    0.837405   0.329110  0.433011  0.296106  0.473252
3    0.036361   0.784073  0.256466  0.654225  0.445484
4    0.045914   0.537175  0.494367  0.963783  0.887703
..        ...        ...       ...       ...       ...
329  0.780272   0.234274  0.057274  0.364951  0.087924
330  0.916470   0.978719  0.614011  0.585698  0.855150
331  0.723955   0.915197  0.202361  0.771998  0.810760
332  0.029631   0.450812  0.085161  0.254788  0.785794
333  0.747321   0.558879  0.072716  0.511503  0.366573

[334 rows x 5 columns]

In [505]:
df.iloc[0][2] = int(67)
df

0          1          2         3         4
0    0.326001  67.000000  67.000000  0.913155  0.103338
1    0.739126   0.146782   0.933030  0.910299  0.089911
2    0.837405   0.329110   0.433011  0.296106  0.473252
3    0.036361   0.784073   0.256466  0.654225  0.445484
4    0.045914   0.537175   0.494367  0.963783  0.887703
..        ...        ...        ...       ...       ...
329  0.780272   0.234274   0.057274  0.364951  0.087924
330  0.916470   0.978719   0.614011  0.585698  0.855150
331  0.723955   0.915197   0.202361  0.771998  0.810760
332  0.029631   0.450812   0.085161  0.254788  0.785794
333  0.747321   0.558879   0.072716  0.511503  0.366573

[334 rows x 5 columns]

In [506]:
df.columns = list("ABCDE")
df

A          B          C         D         E
0    0.326001  67.000000  67.000000  0.913155  0.103338
1    0.739126   0.146782   0.933030  0.910299  0.089911
2    0.837405   0.329110   0.433011  0.296106  0.473252
3    0.036361   0.784073   0.256466  0.654225  0.445484
4    0.045914   0.537175   0.494367  0.963783  0.887703
..        ...        ...        ...       ...       ...
329  0.780272   0.234274   0.057274  0.364951  0.087924
330  0.916470   0.978719   0.614011  0.585698  0.855150
331  0.723955   0.915197   0.202361  0.771998  0.810760
332  0.029631   0.450812   0.085161  0.254788  0.785794
333  0.747321   0.558879   0.072716  0.511503  0.366573

[334 rows x 5 columns]

In [507]:
df.loc[4]['E'] = 88
df

A          B          C         D          E
0    0.326001  67.000000  67.000000  0.913155   0.103338
1    0.739126   0.146782   0.933030  0.910299   0.089911
2    0.837405   0.329110   0.433011  0.296106   0.473252
3    0.036361   0.784073   0.256466  0.654225   0.445484
4    0.045914   0.537175   0.494367  0.963783  88.000000
..        ...        ...        ...       ...        ...
329  0.780272   0.234274   0.057274  0.364951   0.087924
330  0.916470   0.978719   0.614011  0.585698   0.855150
331  0.723955   0.915197   0.202361  0.771998   0.810760
332  0.029631   0.450812   0.085161  0.254788   0.785794
333  0.747321   0.558879   0.072716  0.511503   0.366573

[334 rows x 5 columns]

In [511]:
df.loc[:334,'F'] = 0.50 # Add new columns 'F' 
df

A          B          C         D          E    F
0    0.326001  67.000000  67.000000  0.913155   0.103338  0.5
1    0.739126   0.146782   0.933030  0.910299   0.089911  0.5
2    0.837405   0.329110   0.433011  0.296106   0.473252  0.5
3    0.036361   0.784073   0.256466  0.654225   0.445484  0.5
4    0.045914   0.537175   0.494367  0.963783  88.000000  0.5
..        ...        ...        ...       ...        ...  ...
329  0.780272   0.234274   0.057274  0.364951   0.087924  0.5
330  0.916470   0.978719   0.614011  0.585698   0.855150  0.5
331  0.723955   0.915197   0.202361  0.771998   0.810760  0.5
332  0.029631   0.450812   0.085161  0.254788   0.785794  0.5
333  0.747321   0.558879   0.072716  0.511503   0.366573  0.5

[334 rows x 6 columns]

In [513]:
df.loc[334,:3] = 0.50 # Add new Row 'G' 
df

<ipython-input-513-7c393cc64d20>:1: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  df.loc[334,:3] = 0.50 # Add new columns 'F'


A          B          C         D          E    F
0    0.326001  67.000000  67.000000  0.913155   0.103338  0.5
1    0.739126   0.146782   0.933030  0.910299   0.089911  0.5
2    0.837405   0.329110   0.433011  0.296106   0.473252  0.5
3    0.036361   0.784073   0.256466  0.654225   0.445484  0.5
4    0.045914   0.537175   0.494367  0.963783  88.000000  0.5
..        ...        ...        ...       ...        ...  ...
331  0.723955   0.915197   0.202361  0.771998   0.810760  0.5
332  0.029631   0.450812   0.085161  0.254788   0.785794  0.5
333  0.747321   0.558879   0.072716  0.511503   0.366573  0.5
G    0.500000   0.500000   0.500000       NaN        NaN  NaN
334  0.500000   0.500000   0.500000       NaN        NaN  NaN

[336 rows x 6 columns]

In [515]:
df.dropna()

A          B          C         D          E    F
0    0.326001  67.000000  67.000000  0.913155   0.103338  0.5
1    0.739126   0.146782   0.933030  0.910299   0.089911  0.5
2    0.837405   0.329110   0.433011  0.296106   0.473252  0.5
3    0.036361   0.784073   0.256466  0.654225   0.445484  0.5
4    0.045914   0.537175   0.494367  0.963783  88.000000  0.5
..        ...        ...        ...       ...        ...  ...
329  0.780272   0.234274   0.057274  0.364951   0.087924  0.5
330  0.916470   0.978719   0.614011  0.585698   0.855150  0.5
331  0.723955   0.915197   0.202361  0.771998   0.810760  0.5
332  0.029631   0.450812   0.085161  0.254788   0.785794  0.5
333  0.747321   0.558879   0.072716  0.511503   0.366573  0.5

[334 rows x 6 columns]

In [532]:
df.iloc[:5,:]

A          B          C         D          E    F
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5

In [550]:
df.loc[:4,"G"] = 0.9
df

A          B          C         D          E    F    G
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9

In [549]:
df.fillna(0.8888)
df

A          B          C         D          E    F    G
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9

In [544]:
df.dropna(inplace = True)
df

A          B          C         D          E    F    G
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9

In [552]:
df.loc[2:,"H"] = 0.666
df

A          B          C         D          E    F    G      H
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9    NaN
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9    NaN
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9  0.666
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9  0.666
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9  0.666

In [554]:
df["H"].fillna(130, inplace = True)
df

A          B          C         D          E    F    G        H
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9  130.000
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9  130.000
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9    0.666
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9    0.666
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9    0.666

In [569]:
df.iloc[:2,7] = 'Nan'
df

A          B          C         D          E    F    G      H
0  0.326001  67.000000  67.000000  0.913155   0.103338  0.5  0.9    Nan
1  0.739126   0.146782   0.933030  0.910299   0.089911  0.5  0.9    Nan
2  0.837405   0.329110   0.433011  0.296106   0.473252  0.5  0.9  0.666
3  0.036361   0.784073   0.256466  0.654225   0.445484  0.5  0.9  0.666
4  0.045914   0.537175   0.494367  0.963783  88.000000  0.5  0.9  0.666

In [571]:
np.sum(loc[[2,"A"],[2."B"])

TypeError: cannot perform reduce with flexible type